algoritmo "ParametrosVALORouReferencia"
var
   x, y: inteiro
Procedimento Soma (var a, b: inteiro)
Inicio
      a <- a + 1
      b <- b + 2
      Escreval ("Valor de A = ", a)
      Escreval ("Valor de B = ", b)
      Escreval ("A soma de A + B =", a+b)
FimProcedimento
inicio
      x <- 4
      y <- 8
      Soma (x, y)
      Escreval ("Valor de X = ", x)
      Escreval ("Valor de Y = ", y)
fimalgoritmo